"use client";
import React, { forwardRef } from 'react';
import { useReportData } from '@/context/ReportContext';

const ReportPreview = forwardRef<HTMLDivElement>((props, ref) => {
  const { reportData } = useReportData();
  const { analysis, selectedOptions } = reportData;

  const showFullBreakdown = selectedOptions.includes("full_breakdown");
  const showComparison = selectedOptions.includes("comparison_data");
  const showRiskAnalysis = selectedOptions.includes("risk_analysis");
  const showRecommendations = selectedOptions.includes("recommendations");

  if (!analysis) {
    return (
      <div className="flex-1 p-6 md:p-8 flex items-center justify-center bg-surface-container-lowest/40" ref={ref}>
         <div className="text-center space-y-4 max-w-sm">
            <span className="material-symbols-outlined text-border text-6xl">document_scanner</span>
            <h3 className="font-headline font-bold text-lg text-white">No Analysis Available</h3>
            <p className="text-sm text-on-surface-variant">Please analyze a document using the X-Ray engine before generating a report.</p>
         </div>
      </div>
    );
  }

  // Parse insight numbers if possible, else 0
  // Parse insight numbers if possible, else 0
  const principalFixed = analysis.metrics.loan_amount !== "--" ? analysis.metrics.loan_amount : "₹0";

  return (
    <div className="flex-1 p-6 md:p-8 overflow-y-auto bg-surface-container-lowest/40" ref={ref}>
      <div className="space-y-10">
        {/* HEADER */}
        <div className="flex justify-between items-start">
          <div>
            <div className="text-[10px] font-headline font-bold text-secondary uppercase tracking-[0.2em] mb-2">Algorithm Preview</div>
            <h1 className="text-3xl font-headline font-bold tracking-tighter text-white">Document Analysis Report</h1>
            <p className="text-on-surface-variant text-sm mt-1">Generated by X-Ray Engine • {new Date().toLocaleDateString()}</p>
          </div>
          <div className="p-3 bg-surface-container-high rounded-2xl border border-white/5 shadow-inner">
            <span className="material-symbols-outlined text-secondary" style={{fontVariationSettings: "'FILL' 1"}}>description</span>
          </div>
        </div>

        {/* CONDITION: FULL BREAKDOWN */}
        {showFullBreakdown && (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="md:col-span-2 p-6 rounded-2xl bg-gradient-to-br from-surface-container-high to-surface-container border border-white/5 flex items-center justify-between">
              <div className="space-y-1">
                <h4 className="text-on-surface-variant text-xs font-headline uppercase tracking-wider font-bold">Overall Risk Assessment</h4>
                <div className="flex items-end gap-1">
                    <div className="text-5xl font-headline font-bold text-white tracking-tighter">{analysis.score.toFixed(1)}</div>
                    <div className="text-lg text-secondary mb-1">/10.0</div>
                </div>
                
                <div className="inline-flex items-center gap-1.5 px-2 py-0.5 mt-2 rounded-full bg-tertiary/10 text-tertiary text-[10px] font-bold uppercase tracking-wider">
                  <span className="material-symbols-outlined text-xs">monitoring</span> {analysis.summary.risk_level} Risk
                </div>
              </div>
              <div className="w-24 h-24 relative flex items-center justify-center">
                <svg className="w-full h-full -rotate-90">
                  <circle cx="48" cy="48" fill="transparent" r="40" stroke="rgba(255,255,255,0.05)" strokeWidth="8"></circle>
                  <circle cx="48" cy="48" fill="transparent" r="40" stroke="#4cd7f6" strokeDasharray="251.2" strokeDashoffset={251.2 - (251.2 * (analysis.score * 10)) / 100} strokeWidth="8" className="drop-shadow-[0_0_8px_#4cd7f6]"></circle>
                </svg>
                <span className="absolute material-symbols-outlined text-white/40">shield_with_heart</span>
              </div>
            </div>
            
            <div className="p-6 rounded-2xl border border-white/5 bg-surface-container-high flex flex-col justify-between">
              <h4 className="text-on-surface-variant text-xs font-headline uppercase tracking-wider font-bold">Principal Detected</h4>
              <div>
                <div className="text-2xl font-headline font-bold text-white">{principalFixed}</div>
                <div className="text-tertiary text-xs mt-1">Rate: {analysis.metrics.interest_rate} • Tenure: {analysis.metrics.tenure}</div>
              </div>
            </div>
          </div>
        )}

        {/* CONDITION: RISK ANALYSIS */}
        {showRiskAnalysis && analysis.clauses && analysis.clauses.filter(c => c.type !== 'neutral').length > 0 && (
          <div className="space-y-4">
            <h4 className="text-on-surface-variant text-xs font-headline uppercase tracking-wider font-bold">Priority Clause Analysis</h4>
            <div className="space-y-3">
              {analysis.clauses.filter(c => c.type !== 'neutral').map((clause, idx) => (
                <div key={idx} className="p-4 rounded-xl bg-surface-container border border-white/5 flex flex-col gap-2">
                  <div className="flex justify-between items-start gap-4">
                    <span className="text-sm font-bold text-white leading-tight">"{clause.text}"</span>
                    <span className={`shrink-0 text-[10px] font-bold uppercase px-2 py-0.5 rounded-full ${clause.type === 'high_risk' ? 'bg-error/10 text-error' : clause.type === 'warning' ? 'bg-warning/10 text-warning' : 'bg-primary/10 text-primary'}`}>
                      {clause.type.replace('_', ' ')}
                    </span>
                  </div>
                  <p className="text-xs text-on-surface-variant leading-relaxed text-justify">{clause.reason}</p>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* CONDITION: RECOMMENDATIONS */}
        {showRecommendations && analysis.summary && (
          <div className="space-y-4">
            <h4 className="text-on-surface-variant text-xs font-headline uppercase tracking-wider font-bold">AI Strategic Overview</h4>
            <div className="p-5 rounded-2xl bg-surface-container-high/40 border border-white/5 space-y-4">
              <p className="text-sm text-white/90 leading-relaxed font-body">
                {analysis.summary.overview}
              </p>
              {analysis.summary.key_points && analysis.summary.key_points.length > 0 && (
                <ul className="list-disc pl-5 space-y-2 text-on-surface-variant text-xs md:text-sm">
                  {analysis.summary.key_points.map((point, idx) => (
                    <li key={idx}>
                      <span>{point}</span>
                    </li>
                  ))}
                </ul>
              )}
              
              {/* Fee Extraction in Summary */}
              {analysis.metrics.fees.length > 0 && (
                <div className="mt-4 pt-4 border-t border-white/5">
                   <p className="text-[10px] font-bold text-outline uppercase tracking-widest mb-2">Non-Interest Financial Obligations</p>
                   <div className="flex flex-wrap gap-2">
                      {analysis.metrics.fees.map((fee, i) => (
                         <span key={i} className="px-3 py-1 rounded-lg bg-surface-container text-white text-xs border border-white/5">{fee}</span>
                      ))}
                   </div>
                </div>
              )}
            </div>
          </div>
        )}
        
        {/* CONDITION: COMPARISON */}
        {showComparison && (
           <div className="space-y-4">
            <h4 className="text-on-surface-variant text-xs font-headline uppercase tracking-wider font-bold">Strategic Benchmark Comparison</h4>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
               <div className="p-4 rounded-xl bg-surface-container-high border border-white/5">
                  <p className="text-[10px] font-bold text-outline-variant uppercase mb-1">Penalty APR (Max)</p>
                  <p className="text-xl font-headline font-bold text-error">{analysis.metrics.penalty_apr}</p>
               </div>
               <div className="p-4 rounded-xl bg-surface-container-high border border-white/10">
                  <p className="text-[10px] font-bold text-outline-variant uppercase mb-1">Market Benchmark</p>
                  <p className="text-xl font-headline font-bold text-tertiary">~1/3 lower avg.</p>
               </div>
            </div>
            <p className="text-[10px] text-on-surface-variant italic px-2">Market data extrapolated from current sectoral lending benchmarks.</p>
           </div>
        )}

      </div>
    </div>
  );
});

ReportPreview.displayName = 'ReportPreview';

export default ReportPreview;
